In [1]:
import numpy as np 
import pandas as pd

In [2]:
df = pd.read_csv('./data/features.csv')
df = df.sample(frac=1).reset_index(drop=True)

In [3]:
X = df.iloc[:, :-1].values
Y = df.iloc[:, -1].values

In [4]:
# from sklearn.linear_model import LogisticRegression


# log_reg = LogisticRegression(max_iter=150)
# log_reg.fit(X, Y)
# print("")

In [5]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=95, criterion='entropy', random_state=25)
rf.fit(X, Y)
print("")

In [6]:
test = pd.read_csv('./data/test/features.csv')

In [7]:
X_test = test.iloc[:, :-1].values
Y_test = test.iloc[:, -1].values

In [8]:
Y_pred = rf.predict(X_test)

In [9]:
Y_pred[:10]

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0], dtype=int64)

In [10]:
Y_test[:10]

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 1], dtype=int64)

In [11]:
from sklearn.metrics import accuracy_score

score = accuracy_score(Y_test, Y_pred)
print('model accuracy ', score)

model accuracy  0.917


In [12]:
rf.feature_importances_

array([0.06490406, 0.06183015, 0.09033437, 0.01523445, 0.05923563,
       0.04719966, 0.04686638, 0.26975824, 0.15236471, 0.1286733 ,
       0.06359906])

In [22]:
import joblib


joblib.dump(rf, './models/model_91_7_latest.mu')

['./models/model_91_7_latest.mu']

In [14]:
# import joblib


# model = joblib.load('./models/model_90_7.mu')

In [15]:
import importlib
import predict as predict
import algo as algo

In [16]:
from sardinas_patterson import sardinas_patterson


sardinas_patterson({'000010','010110','001','00','110','101011','0011100','1110','1100101','00011'})

False

In [17]:
importlib.reload(predict)
importlib.reload(algo)

<module 'algo' from 'c:\\Users\\Mialisoa\\ITU\\S6\\codage\\algo\\ml\\algo.py'>

In [18]:
importlib.reload(predict)
importlib.reload(algo)
data_nante = [
    {'1100111', '0010100', '010', '011', '1100', '110'},
{'11', '0011111', '10010', '101111', '001101'},
{'1110100', '1'},
{'11101', '111', '1000110', '10110', '01', '1001011', '010', '01001'},
{'01110', '1011000', '100', '1', '10', '011000', '1010010', '1001'},
{'01001', '1', '1101111', '11110'},
]

nante_vrai = [1,1,1,0,0,0]

nante_predict = predict.predict_list(rf, data_nante)
print('tests accuracy')
accuracy_score(nante_vrai, nante_predict)

tests accuracy


0.8333333333333334

In [19]:
importlib.reload(algo)
test_code = pd.read_csv('./data/test/code.csv')

codes = algo.format_to_set(test_code)
    
    # CODE, raha tsy code d 0
test_y_vrai = [1 for i in range(len(codes))]
test_y_predict = predict.predict_list(rf, codes)
print('score tsy code')
accuracy_score(test_y_vrai, test_y_predict)

score tsy code


0.9019019019019019

In [20]:
langages = [
    {'0100011', '011011', '001', '0110000', '0101110', '101', '0000011', '00101', '00110'},
    {'0101000', '0100', '1100011', '0110', '10111', '01', '0110110', '110101'},
    {'000001', '1', '100000', '1011100', '000000'},
    {'10100', '10010', '11100', '10'},
    {'00', '0000', '1000001'},
    {'0', '000', '11000'},
    {'1011101', '10101', '1011', '0111011'},
    {'1101', '000', '00'},
    {'1101011', '010001', '1010', '10000', '0'},
    {'00001', '000', '00', '1100011', '1100101'},
    {'001', '110110', '110', '10'},
    {'00', '10', '01011', '10011', '10111'},
    {'111001', '10011', '00', '0000', '0000111'}
]

# langages = [
#     "011;1101010;010;00001;100;0000110",
# "011;011001;00101;000111;0000;0100",
# "1111000;001111;110010;10110;0110;111",
# "1001010;100;100111;11;0110110;011101;0;0111101",
# "000;101;111110;01;0000;0;1",
# "010100;11;00;0000;0001100;1101000;0101010;0010111",
# "101;0101;0101111;01;11001;00;11;101011;0011110;0",
# ]
#
ok = 0
for langage in langages :
    prediction = predict.predict_langage(rf, langage)
    # #
    sardinas = sardinas_patterson(langage)

    if(sardinas == prediction) :
        ok = ok +1
    # print('L:', langage, ' S: ', sardinas, ' P: ', prediction)

print('ok ', ok, ' / ', len(langages))

ok  5  /  13


In [21]:
importlib.reload(predict)
predict.predict(rf, "101010;110001;0111;11;11001;1010100;0010000")

{'pred': 1, 'verdict': 1}